// src/screens/screenCodes.ts

import type { ScreenCode } from "../screens/types";

export function makeScreenCode(
  menu: number,
  submenu: number,
  page: number,
): ScreenCode {
  return ((menu & 0xff) << 16) | ((submenu & 0xff) << 8) | (page & 0xff);
}

export function screenMenu(code: ScreenCode): number {
  return (code >> 16) & 0xff;
}

export function screenSubmenu(code: ScreenCode): number {
  return (code >> 8) & 0xff;
}

export function screenPage(code: ScreenCode): number {
  return code & 0xff;
}

export const SCREEN_CODE_NONE = 0x000000;

export const SCREEN_CODE_CORE_STARTUP = 0x010001;
export const SCREEN_CODE_CORE_DASHBOARD = 0x010101;
export const SCREEN_CODE_CORE_MODE_CHANGE = 0x010102;
export const SCREEN_CODE_CORE_STABILIZE_PROMPT = 0x010103;
export const SCREEN_CODE_CORE_MODE_PROMPT = 0x010104;
export const SCREEN_CODE_CORE_REMOTE_MODE_CHANGED = 0x010105;
export const SCREEN_CODE_CORE_MAIN_MENU = 0x010201;

export const SCREEN_CODE_CONNECTIVITY_WIFI_MENU = 0x020101;
export const SCREEN_CODE_CONNECTIVITY_WIFI_STATUS = 0x020201;
export const SCREEN_CODE_CONNECTIVITY_WIFI_SEARCHING = 0x020202;
export const SCREEN_CODE_CONNECTIVITY_WIFI_RESULTS = 0x020203;
export const SCREEN_CODE_CONNECTIVITY_WIFI_NOT_CONNECTED = 0x020204;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CONNECTING = 0x020205;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CONNECTED = 0x020206;
export const SCREEN_CODE_CONNECTIVITY_WIFI_SEARCH_COMPLETE = 0x020207;
export const SCREEN_CODE_CONNECTIVITY_WIFI_SEARCH_CANCELED = 0x020208;
export const SCREEN_CODE_CONNECTIVITY_WIFI_DETAILS = 0x020209;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CREDENTIALS_WEB = 0x02020a;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CREDENTIALS_SUCCEEDED = 0x02020b;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CREDENTIALS_FAILED = 0x02020c;
export const SCREEN_CODE_CONNECTIVITY_WIFI_CREDENTIALS_AT = 0x02020d;

export const SCREEN_CODE_CONNECTIVITY_ESP_MENU = 0x020301;
export const SCREEN_CODE_CONNECTIVITY_ESP_CHECKING = 0x020302;
export const SCREEN_CODE_CONNECTIVITY_ESP_FIRMWARE_REQUEST = 0x020303;
export const SCREEN_CODE_CONNECTIVITY_ESP_RESET_SENT = 0x020304;
export const SCREEN_CODE_CONNECTIVITY_ESP_CHECK_REQUIRED = 0x020305;
export const SCREEN_CODE_CONNECTIVITY_ESP_BOOT_RECEIVED = 0x020306;
export const SCREEN_CODE_CONNECTIVITY_ESP_FIRMWARE_RECEIVED = 0x020307;
export const SCREEN_CODE_CONNECTIVITY_ESP_MODE_CHANGED = 0x020308;
export const SCREEN_CODE_CONNECTIVITY_ESP_AP_STARTED = 0x020309;
export const SCREEN_CODE_CONNECTIVITY_ESP_REBOOT_MODE = 0x02030a;
export const SCREEN_CODE_CONNECTIVITY_ESP_UNRESPONSIVE = 0x02030b;
export const SCREEN_CODE_CONNECTIVITY_ESP_WATCHDOG_RESET = 0x02030c;
export const SCREEN_CODE_CONNECTIVITY_ESP_EXCEPTION_RESET = 0x02030d;

export const SCREEN_CODE_CONNECTIVITY_USB_CONNECTED = 0x020401;
export const SCREEN_CODE_CONNECTIVITY_USB_DISCONNECTED = 0x020402;

export const SCREEN_CODE_CONNECTIVITY_WEB_SERVER_UP = 0x020501;
export const SCREEN_CODE_CONNECTIVITY_WEB_CLIENT_CONNECTED = 0x020502;
export const SCREEN_CODE_CONNECTIVITY_WEB_CLIENT_DISCONNECTED = 0x020503;
export const SCREEN_CODE_CONNECTIVITY_AP_DEVICE_CONNECTED = 0x020601;
export const SCREEN_CODE_CONNECTIVITY_AP_DEVICE_DISCONNECTED = 0x020602;

export const SCREEN_CODE_SENSORS_MENU = 0x030101;
export const SCREEN_CODE_SENSORS_IR_MENU = 0x030200;
export const SCREEN_CODE_SENSORS_IR_VALUES = 0x030201;
export const SCREEN_CODE_SENSORS_ROUTE_ALIGNMENT = 0x030202;
export const SCREEN_CODE_SENSORS_MPU_MENU = 0x030300;
export const SCREEN_CODE_SENSORS_MPU_VALUES = 0x030301;
export const SCREEN_CODE_SENSORS_MPU_STREAM_STARTED = 0x030302;
export const SCREEN_CODE_SENSORS_MPU_STREAM_STOPPED = 0x030303;
export const SCREEN_CODE_SENSORS_MPU_CALIBRATION = 0x030304;
export const SCREEN_CODE_SENSORS_MPU_CALIBRATION_NOTICE = 0x030305;
export const SCREEN_CODE_SENSORS_MPU_CALIBRATION_DONE = 0x030306;
export const SCREEN_CODE_SENSORS_RADAR = 0x030401;
export const SCREEN_CODE_SENSORS_DISPLAY_MENU = 0x030500;
export const SCREEN_CODE_SENSORS_DISPLAY_ROTATION_TEST = 0x030501;
export const SCREEN_CODE_SENSORS_DISPLAY_ROTATION_MPU_TEST = 0x030502;
export const SCREEN_CODE_SENSORS_DISPLAY_OLED_CANVAS = 0x030503;

export const SCREEN_CODE_MOTOR_MENU = 0x040100;
export const SCREEN_CODE_MOTOR_TEST = 0x040101;
export const SCREEN_CODE_MOTOR_LEFT_TEST = 0x040102;
export const SCREEN_CODE_MOTOR_RIGHT_TEST = 0x040103;
export const SCREEN_CODE_BALANCE_MENU = 0x040200;
export const SCREEN_CODE_BALANCE_PID_STATUS = 0x040201;
export const SCREEN_CODE_BALANCE_PID_LOG = 0x040202;
export const SCREEN_CODE_BALANCE_PID_KP = 0x040203;
export const SCREEN_CODE_BALANCE_PID_KI = 0x040204;
export const SCREEN_CODE_BALANCE_PID_KD = 0x040205;

export const SCREEN_CODE_SETTINGS_MENU = 0x050101;
export const SCREEN_CODE_SETTINGS_ABOUT_MENU = 0x050200;
export const SCREEN_CODE_SETTINGS_ABOUT_PROJECT = 0x050201;
export const SCREEN_CODE_SETTINGS_ABOUT_REPO = 0x050202;
export const SCREEN_CODE_SETTINGS_ABOUT_BUILD = 0x050203;
export const SCREEN_CODE_SETTINGS_WARNING_TIME = 0x050301;
export const SCREEN_CODE_SETTINGS_PREFS_MENU = 0x050400;
export const SCREEN_CODE_SETTINGS_PREFS_ENCODER_MENU = 0x050401;
export const SCREEN_CODE_SETTINGS_PREFS_ENCODER_INVERT = 0x050402;
export const SCREEN_CODE_SETTINGS_PREFS_DISPLAY_MENU = 0x050403;
export const SCREEN_CODE_SETTINGS_PREFS_DISPLAY_LOCK = 0x050404;
export const SCREEN_CODE_SETTINGS_PREFS_DISPLAY_TIMEOUT = 0x050405;
export const SCREEN_CODE_SETTINGS_PREFS_MOTORS_MENU = 0x050406;
export const SCREEN_CODE_SETTINGS_PREFS_MOTOR_PWM_MENU = 0x050407;
export const SCREEN_CODE_SETTINGS_PREFS_MOTOR_PWM_LEFT = 0x050408;
export const SCREEN_CODE_SETTINGS_PREFS_MOTOR_PWM_RIGHT = 0x050409;
export const SCREEN_CODE_SETTINGS_PREFS_SYSTEM_MENU = 0x05040a;
export const SCREEN_CODE_SETTINGS_PREFS_SYSTEM_ACTION_TIMEOUT = 0x05040b;
export const SCREEN_CODE_SETTINGS_PREFS_ROTATION_MENU = 0x05040c;
export const SCREEN_CODE_SETTINGS_PREFS_ROTATION_TEST = 0x05040d;
export const SCREEN_CODE_SETTINGS_PREFS_ROTATION_MPU_TEST = 0x05040e;
export const SCREEN_CODE_SETTINGS_PREFS_ROTATION_AUTO = 0x05040f;
export const SCREEN_CODE_SETTINGS_PREFS_UNER_ROUTER_MENU = 0x050410;
export const SCREEN_CODE_SETTINGS_PREFS_UNER_ROUTER_FORWARDING = 0x050411;
export const SCREEN_CODE_SETTINGS_PREFS_LINE_MENU = 0x050412;
export const SCREEN_CODE_SETTINGS_PREFS_LINE_WIDTH = 0x050413;
export const SCREEN_CODE_SETTINGS_PREFS_SYSTEM_USB_ALIVE = 0x050414;
export const SCREEN_CODE_SETTINGS_PREFS_SECURITY_MENU = 0x050415;
export const SCREEN_CODE_SETTINGS_PREFS_SECURITY_PIN_LOCK = 0x050416;
export const SCREEN_CODE_SETTINGS_PREFS_UNER_FORWARDING_ENABLED = 0x050417;
export const SCREEN_CODE_SETTINGS_PREFS_UNER_FORWARDING_DISABLED = 0x050418;

export const SCREEN_CODE_DIAG_CONTROLLER_CONNECTED = 0x060101;
export const SCREEN_CODE_DIAG_CONTROLLER_DISCONNECTED = 0x060102;
export const SCREEN_CODE_DIAG_COMMAND_RECEIVED = 0x060201;
export const SCREEN_CODE_DIAG_PING_RECEIVED = 0x060202;
export const SCREEN_CODE_DIAG_ESP_CONN_SUCCEEDED = 0x060301;
export const SCREEN_CODE_DIAG_ESP_CONN_FAILED = 0x060302;

export const SCREEN_CODE_SERVICE_TEST_SCREEN = 0x070101;
export const SCREEN_CODE_SERVICE_UNER_ROUTER_MENU = 0x070200;
export const SCREEN_CODE_SERVICE_UNER_ROUTER_USB = 0x070201;
export const SCREEN_CODE_SERVICE_UNER_ROUTER_UART = 0x070202;
export const SCREEN_CODE_SERVICE_UNER_ROUTER_NRF = 0x070203;

export const SCREEN_CODE_WARNING_LOCKED = 0x080101;
export const SCREEN_CODE_WARNING_PIN_INCORRECT = 0x080102;
export const SCREEN_CODE_WARNING_PIN_MODIFIED = 0x080103;
export const SCREEN_CODE_WARNING_PIN_ENTRY = 0x080104;
export const SCREEN_CODE_WARNING_PIN_WAITING = 0x080105;
export const SCREEN_CODE_WARNING_PIN_DENIED = 0x080106;
export const SCREEN_CODE_WARNING_PIN_TIMEOUT = 0x080107;
export const SCREEN_CODE_WARNING_PIN_BLOCKED = 0x080108;
export const SCREEN_CODE_WARNING_PERMISSION_DENIED = 0x080109;
export const SCREEN_CODE_WARNING_REMOTE_AUTHENTICATED = 0x08010a;
export const SCREEN_CODE_WARNING_PIN_CORRECT = 0x08010b;
export const SCREEN_CODE_WARNING_PIN_BYPASSED = 0x08010c;

export interface ScreenDefinition {
  code: ScreenCode;
  isValidationScreen?: boolean;
  pinDigitsCount?: number;
}

export const SCREEN_REPORT_SOURCE_PERMISSION = 0x04;

export const SCREEN_DEFINITIONS: Partial<Record<ScreenCode, ScreenDefinition>> =
  {
    [SCREEN_CODE_WARNING_PIN_ENTRY]: {
      code: SCREEN_CODE_WARNING_PIN_ENTRY,
      isValidationScreen: true,
      pinDigitsCount: 4,
    },
    [SCREEN_CODE_WARNING_PIN_WAITING]: {
      code: SCREEN_CODE_WARNING_PIN_WAITING,
      isValidationScreen: true,
      pinDigitsCount: 4,
    },
    [SCREEN_CODE_WARNING_PIN_DENIED]: {
      code: SCREEN_CODE_WARNING_PIN_DENIED,
      isValidationScreen: true,
      pinDigitsCount: 4,
    },
    [SCREEN_CODE_WARNING_PIN_TIMEOUT]: {
      code: SCREEN_CODE_WARNING_PIN_TIMEOUT,
      isValidationScreen: true,
      pinDigitsCount: 4,
    },
    [SCREEN_CODE_WARNING_PIN_BLOCKED]: {
      code: SCREEN_CODE_WARNING_PIN_BLOCKED,
      isValidationScreen: true,
      pinDigitsCount: 4,
    },
  };

export function getScreenDefinition(
  code: ScreenCode | null | undefined,
): ScreenDefinition | null {
  if (typeof code !== "number") {
    return null;
  }

  return SCREEN_DEFINITIONS[code] ?? null;
}

export function isValidationScreenCode(
  code: ScreenCode | null | undefined,
): boolean {
  return getScreenDefinition(code)?.isValidationScreen === true;
}

export function isPermissionValidationScreenCode(
  code: ScreenCode | null | undefined,
  source?: number,
): boolean {
  if (!isValidationScreenCode(code)) {
    return false;
  }

  if (code === SCREEN_CODE_WARNING_PIN_ENTRY) {
    return source === SCREEN_REPORT_SOURCE_PERMISSION;
  }

  return true;
}

export function getValidationPinDigitsCount(
  code: ScreenCode | null | undefined,
): number {
  const def = getScreenDefinition(code);
  if (!def?.isValidationScreen) {
    return 0;
  }

  return Math.max(1, def.pinDigitsCount ?? 4);
}
