import type { CommandDefinition, CommandGroup } from "./types";

export const IDLE_SUMMARY = "Todavia no se analizo ninguna entrada.";

export const NODE_OPTIONS = [
  { value: "1", label: "0x1 - MCU" },
  { value: "2", label: "0x2 - ESP / PC bridge" },
  { value: "3", label: "0x3 - Web App" },
  { value: "4", label: "0x4 - NRF remoto" },
  { value: "15", label: "0xF - Broadcast" },
];

export const NODE_NAMES: Record<number, string> = {
  0x1: "MCU",
  0x2: "ESP / PC bridge",
  0x3: "Web App",
  0x4: "NRF remoto",
  0xf: "Broadcast",
};

const NETWORK_INTERFACE_OPTIONS = [
  { value: "1", label: "0x01 - STA" },
  { value: "2", label: "0x02 - AP" },
];

const NETWORK_IP_FIELDS: CommandDefinition["fields"] = [
  {
    id: "iface",
    label: "Interfaz",
    type: "select",
    options: NETWORK_INTERFACE_OPTIONS,
  },
  { id: "ip0", label: "IP byte 0", type: "u8", placeholder: "192" },
  { id: "ip1", label: "IP byte 1", type: "u8", placeholder: "168" },
  { id: "ip2", label: "IP byte 2", type: "u8", placeholder: "1" },
  { id: "ip3", label: "IP byte 3", type: "u8", placeholder: "10" },
];

export const COMMAND_GROUPS: CommandGroup[] = [
  {
    label: "WiFi - modo",
    commands: ["0x10", "0x11", "0x12", "0x13", "0x4A", "0x4E"],
  },
  {
    label: "WiFi - conexion",
    commands: ["0x14", "0x15", "0x18", "0x1A", "0x48", "0x49", "0x4B", "0x4C"],
  },
  { label: "Telemetria", commands: ["0x20", "0x21", "0x22"] },
  {
    label: "Estado e info",
    commands: [
      "0x30",
      "0x31",
      "0x40",
      "0x41",
      "0x44",
      "0x45",
      "0x46",
      "0x47",
      "0x4D",
      "0x5B",
    ],
  },
  {
    label: "UI / pantalla",
    commands: ["0x51", "0x52", "0x53", "0x54", "0x55"],
  },
  { label: "Notificaciones IP / boot", commands: ["0x4F", "0x50"] },
  { label: "Sistema", commands: ["0x16", "0x17", "0x19", "0x42", "0x43"] },
  { label: "ACK / control", commands: ["0xE0", "0xE1"] },
  {
    label: "Eventos",
    commands: [
      "0x80",
      "0x81",
      "0x82",
      "0x83",
      "0x84",
      "0x85",
      "0x86",
      "0x87",
      "0x88",
      "0x89",
      "0x8A",
      "0x8B",
      "0x8C",
      "0x8D",
      "0x8E",
      "0x8F",
      "0x90",
      "0x91",
      "0x92",
      "0x93",
      "0x94",
      "0x96",
      "0x97",
    ],
  },
];

export const FRAME_COMMANDS: Record<string, CommandDefinition> = {
  "0x10": {
    name: "SET_MODE_AP",
    desc: "Cambia WiFi a modo AP y levanta SoftAP con credenciales guardadas.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x11": {
    name: "SET_MODE_STA",
    desc: "Cambia a modo STA e inicia conexion con credenciales STA guardadas.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x12": {
    name: "SET_CREDENTIALS",
    desc: "Guarda credenciales AP o STA en NVS. Payload: [target, ssid_len, ssid..., pass_len, pass...]",
    fields: [
      {
        id: "target",
        label: "Target",
        type: "select",
        options: [
          { value: "0", label: "0 - AP" },
          { value: "1", label: "1 - STA" },
        ],
      },
      { id: "ssid", label: "SSID", type: "str", placeholder: "MiWifi" },
      { id: "pass", label: "Password", type: "str", placeholder: "Clave1234" },
    ],
    minPayload: 3,
    maxPayload: 255,
    kind: "request",
  },
  "0x13": {
    name: "CLEAR_CREDENTIALS",
    desc: "Restaura credenciales por defecto y guarda en NVS.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x14": {
    name: "START_SCAN",
    desc: "Inicia escaneo WiFi asincrono. Al terminar llega CMD=0x15 con payload [0xFE].",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x15": {
    name: "GET_SCAN_RESULTS",
    desc: "Devuelve estado/resultados del scan. Tambien puede aparecer como notificacion final con payload [0xFE].",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "mixed",
  },
  "0x16": {
    name: "REBOOT_ESP",
    desc: "Solicita reinicio del ESP. Payload fijo de 1 byte: [boot_mode], donde 0x00 = reinicio normal y 0x01 = reinicio forzado en modo AP.",
    fields: [
      {
        id: "bootMode",
        label: "Modo de arranque",
        type: "select",
        options: [
          { value: "0", label: "0 - Reinicio normal" },
          { value: "1", label: "1 - Reinicio en modo AP" },
        ],
      },
    ],
    minPayload: 1,
    maxPayload: 1,
    kind: "request",
  },
  "0x17": {
    name: "FACTORY_RESET",
    desc: "Alias de CLEAR_CREDENTIALS. Restaura credenciales por defecto.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x18": {
    name: "STOP_SCAN",
    desc: "Detiene escaneo, borra resultados temporales. Dispara notificacion 0x15 [0xFE].",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x19": {
    name: "RESET_MCU",
    desc: "Reinicia el STM32. La web lo envia como stmPacket con payload.data; la ESP valida y reenvia el frame UNER v2 con ruta ESP/PC -> MCU (0x21).",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x1A": {
    name: "WIFI_GET_DETAIL",
    desc: "Consulta el detalle de una red detectada o cacheada por SSID. Request: [ssid_len, ssid...]. Response en el mismo CMD: [ssid_len, ssid..., signalStrength_i8, encryptionType_u8, channel_u8].",
    fields: [{ id: "ssid", label: "SSID", type: "str", placeholder: "MiWifi" }],
    minPayload: 2,
    maxPayload: 35,
    kind: "request",
  },
  "0x20": {
    name: "TELEMETRY_SET_RATE",
    desc: "Inicia, actualiza o detiene el stream de telemetria. Payload u16 LE: [periodMsLow, periodMsHigh]. periodMs > 0 inicia/actualiza; periodMs = 0 envia el finalizador explicito 00 00.",
    fields: [
      { id: "periodLow", label: "Periodo low", type: "u8", placeholder: "200" },
      { id: "periodHigh", label: "Periodo high", type: "u8", placeholder: "0" },
    ],
    minPayload: 2,
    maxPayload: 2,
    kind: "request",
  },
  "0x21": {
    name: "TELEMETRY_ACK",
    desc: "ACK de telemetria. Payload: [code, periodMsLow, periodMsHigh]. code=0 indica OK y periodMs confirma la tasa aplicada.",
    fields: [],
    minPayload: 3,
    maxPayload: 3,
    kind: "ack",
  },
  "0x22": {
    name: "TELEMETRY_DATA",
    desc: "Dato de telemetria MPU6050. Payload esperado de 17 bytes: [schema, seqL, seqH, accXl, accXh, accYl, accYh, accZl, accZh, gyroXl, gyroXh, gyroYl, gyroYh, gyroZl, gyroZh, tempL, tempH].",
    fields: [],
    minPayload: 17,
    maxPayload: 17,
    kind: "event",
  },
  "0x30": {
    name: "GET_STATUS",
    desc: "Devuelve estado general: ap_active, wifi_active, wifi_info, sta_ip, ap_ip.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x31": {
    name: "PING",
    desc: "Ping logico. Responde status=0 sin datos extra.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x40": {
    name: "GET_PREFERENCES",
    desc: "Devuelve SSIDs guardados de AP y STA (sin passwords).",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x41": {
    name: "REQUEST_FIRMWARE",
    desc: "Devuelve string de version de firmware ASCII.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x42": {
    name: "ECHO",
    desc: "Eco exacto del payload. En la spec normal son 4 bytes.",
    fields: [
      { id: "b0", label: "Byte 0", type: "hex1", placeholder: "11" },
      { id: "b1", label: "Byte 1", type: "hex1", placeholder: "22" },
      { id: "b2", label: "Byte 2", type: "hex1", placeholder: "33" },
      { id: "b3", label: "Byte 3", type: "hex1", placeholder: "44" },
    ],
    minPayload: 4,
    maxPayload: 4,
    kind: "request",
  },
  "0x43": {
    name: "SET_ENCODER_FAST",
    desc: "Configura parametro de encoder rapido (un byte).",
    fields: [{ id: "val", label: "Valor", type: "hex1", placeholder: "01" }],
    minPayload: 1,
    maxPayload: 1,
    kind: "request",
  },
  "0x44": {
    name: "GET_CONNECTED_USERS",
    desc: "Devuelve cantidad de clientes WebSocket conectados.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x45": {
    name: "GET_USER_INFO",
    desc: "Consulta info de cliente WS por indice (id LE 4 bytes + IP 4 bytes).",
    fields: [
      { id: "idx", label: "Indice de usuario", type: "u8", placeholder: "0" },
    ],
    minPayload: 1,
    maxPayload: 1,
    kind: "request",
  },
  "0x46": {
    name: "GET_INTERFACES_CONNECTED",
    desc: "Estado de interfaces logicas: [PC, WEB, RF, ESP].",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x47": {
    name: "GET_CREDENTIALS",
    desc: "Devuelve STA + AP completas (passwords en claro).",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x48": {
    name: "CONNECT_WIFI",
    desc: "Intenta conexion STA con credenciales guardadas. Push [0xFE, ipx4] al conectar.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "mixed",
  },
  "0x49": {
    name: "DISCONNECT_WIFI",
    desc: "Desconecta STA y deshabilita auto-reconnect interno.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x51": {
    name: "GET_CURRENT_SCREEN",
    desc: "Solicita al MCU el snapshot actual de pantalla para resincronizar el visor web.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x52": {
    name: "REQUEST_SCREEN_PAGE",
    desc: "Pide al MCU cambiar la página visible de una screen concreta. El payload incluye el screenCode para validar que el request aplica a la pantalla esperada.",
    fields: [
      {
        id: "screenCode",
        label: "Código de pantalla",
        type: "hex4",
        placeholder: "00000000",
      },
      { id: "direction", label: "Dirección", type: "hex1", placeholder: "00" },
    ],
    minPayload: 5,
    maxPayload: 5,
    kind: "request",
  },
  "0x53": {
    name: "MENU_ITEM_CLICK",
    desc: "Emula en el MCU un click físico sobre uno de los tres items visibles del menú actual. El payload incluye el screenCode y el número de item visible.",
    fields: [
      {
        id: "screenCode",
        label: "Código de pantalla",
        type: "hex4",
        placeholder: "00000000",
      },
      { id: "item", label: "Item", type: "hex1", placeholder: "01" },
    ],
    minPayload: 5,
    maxPayload: 5,
    kind: "request",
  },
  "0x54": {
    name: "TRIGGER_ENCODER_BUTTON",
    desc: "Emula el botón del encoder en el MCU. El payload distingue entre shortpress y longpress y valida contra el screenCode actual.",
    fields: [
      {
        id: "screenCode",
        label: "Código de pantalla",
        type: "hex4",
        placeholder: "00000000",
      },
      { id: "pressKind", label: "Tipo de pulsación", type: "hex1", placeholder: "00" },
    ],
    minPayload: 5,
    maxPayload: 5,
    kind: "request",
  },
  "0x55": {
    name: "TRIGGER_USER_BUTTON",
    desc: "Emula el botón de usuario en el MCU. El payload distingue entre shortpress y longpress y valida contra el screenCode actual.",
    fields: [
      {
        id: "screenCode",
        label: "Código de pantalla",
        type: "hex4",
        placeholder: "00000000",
      },
      { id: "pressKind", label: "Tipo de pulsación", type: "hex1", placeholder: "00" },
    ],
    minPayload: 5,
    maxPayload: 5,
    kind: "request",
  },
  "0x5B": {
    name: "GET_CAR_MODE",
    desc: "Consulta al STM el modo actual del auto. Es un CMD request/response: la web envia 0x5B sin payload y la STM responde en el mismo CMD con payload [carMode], donde carMode es (uint8_t)GET_CAR_MODE(): 0=IDLE_MODE, 1=FOLLOW_MODE, 2=TEST_MODE. CAR_MODE_MAX=3. No es un evento puro.",
    fields: [],
    minPayload: 0,
    maxPayload: 1,
    kind: "request",
  },
  "0x4A": {
    name: "SET_AP_CONFIG",
    desc: "Actualiza credenciales AP (SSID y password). Payload: [ssid_len, ssid..., pass_len, pass...]",
    fields: [
      {
        id: "ssid",
        label: "SSID del AP",
        type: "str",
        placeholder: "ESP_TEST",
      },
      {
        id: "pass",
        label: "Password del AP",
        type: "str",
        placeholder: "12345678",
      },
    ],
    minPayload: 2,
    maxPayload: 255,
    kind: "request",
  },
  "0x4B": {
    name: "START_AP",
    desc: "Arranca SoftAP con config actual. Push [0xFE, ipx4] cuando queda activo.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "mixed",
  },
  "0x4C": {
    name: "STOP_AP",
    desc: "Apaga SoftAP.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x4D": {
    name: "GET_CONNECTED_USERS_MODE",
    desc: "Resumen: [ap_mode, ap_users, ws_users].",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "request",
  },
  "0x4E": {
    name: "SET_AUTO_RECONNECT",
    desc: "Habilita/deshabilita auto reconexion STA. Responde [status, enabled_now].",
    fields: [
      {
        id: "en",
        label: "Estado",
        type: "select",
        options: [
          { value: "1", label: "1 - Habilitar" },
          { value: "0", label: "0 - Deshabilitar" },
        ],
      },
    ],
    minPayload: 1,
    maxPayload: 1,
    kind: "request",
  },
  "0x4F": {
    name: "BOOT_COMPLETE",
    desc: "Notificacion de boot completo con interfaz e IP activa. Payload fijo: [if, ip0, ip1, ip2, ip3].",
    fields: NETWORK_IP_FIELDS,
    minPayload: 5,
    maxPayload: 5,
    kind: "event",
  },
  "0x50": {
    name: "NETWORK_IP",
    desc: "Notifica interfaz e IP activa. Payload fijo: [if, ip0, ip1, ip2, ip3].",
    fields: NETWORK_IP_FIELDS,
    minPayload: 5,
    maxPayload: 5,
    kind: "event",
  },
  "0x80": {
    name: "EVT_BOOT",
    desc: "Emitido al iniciar la app.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x81": {
    name: "EVT_MODE_CHANGED",
    desc: "Emitido cuando cambia el modo WiFi.",
    fields: [
      {
        id: "mode",
        label: "Modo",
        type: "select",
        options: [
          { value: "16", label: "0x10 - AP" },
          { value: "17", label: "0x11 - STA" },
        ],
      },
    ],
    minPayload: 1,
    maxPayload: 1,
    kind: "event",
  },
  "0x82": {
    name: "EVT_STA_CONNECTED",
    desc: "STA conectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x83": {
    name: "EVT_STA_DISCONNECTED",
    desc: "STA desconectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x84": {
    name: "EVT_AP_CLIENT_JOIN",
    desc: "Cliente se conecta al SoftAP.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x85": {
    name: "EVT_AP_CLIENT_LEAVE",
    desc: "Cliente sale del SoftAP.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x86": {
    name: "EVT_APP_USER_CONNECTED",
    desc: "Usuario app conectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x87": {
    name: "EVT_APP_USER_DISCONNECTED",
    desc: "Usuario app desconectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x88": {
    name: "EVT_WEBSERVER_UP",
    desc: "Servidor HTTP levantado.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "event",
  },
  "0x89": {
    name: "EVT_WEBSERVER_CLIENT_CONNECTED",
    desc: "Cliente web conectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x8A": {
    name: "EVT_WEBSERVER_CLIENT_DISCONNECTED",
    desc: "Cliente web desconectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x8B": {
    name: "EVT_LASTWIFI_NOTFOUND",
    desc: "Evento definido en tabla.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x8C": {
    name: "EVT_CONTROLLER_CONNECTED",
    desc: "Controlador conectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x8D": {
    name: "EVT_CONTROLLER_DISCONNECTED",
    desc: "Controlador desconectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x8E": {
    name: "EVT_USB_CONNECTED",
    desc: "USB conectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "event",
  },
  "0x8F": {
    name: "EVT_USB_DISCONNECTED",
    desc: "USB desconectado.",
    fields: [],
    minPayload: 0,
    maxPayload: 0,
    kind: "event",
  },
  "0x90": {
    name: "EVT_APP_GET_MPU_READINGS",
    desc: "Evento definido para lecturas MPU.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x91": {
    name: "EVT_APP_GET_TCRT_READINGS",
    desc: "Evento definido para lecturas TCRT.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x92": {
    name: "EVT_WIFI_CONNECTED",
    desc: "WiFi conectado; expone credenciales STA.",
    fields: [],
    minPayload: 0,
    maxPayload: 255,
    kind: "event",
  },
  "0x93": {
    name: "EVT_NETWORK_IP",
    desc: "Evento de interfaz/IP activa. Payload fijo: [if, ip0, ip1, ip2, ip3].",
    fields: NETWORK_IP_FIELDS,
    minPayload: 5,
    maxPayload: 5,
    kind: "event",
  },
  "0x94": {
    name: "EVT_BOOT_COMPLETE",
    desc: "Evento de boot completo con interfaz e IP. Payload fijo: [if, ip0, ip1, ip2, ip3].",
    fields: NETWORK_IP_FIELDS,
    minPayload: 5,
    maxPayload: 5,
    kind: "event",
  },
  "0x96": {
    name: "EVT_MENU_SELECTION_CHANGED",
    desc: "Evento emitido por la STM cuando entra a un menu o cambia el item seleccionado. Payload: [screen_code_le(4), selected_index, item_count, source]. La web lo normaliza como screen.changed para actualizar el preview.",
    fields: [],
    minPayload: 5,
    maxPayload: 7,
    kind: "event",
  },
  "0x97": {
    name: "EVT_CAR_MODE_CHANGED",
    desc: "Evento propio emitido por la STM cuando empuja el modo actual del auto hacia la web. Payload fijo: [carMode], donde carMode es GET_CAR_MODE(): 0=IDLE_MODE, 1=FOLLOW_MODE, 2=TEST_MODE.",
    fields: [],
    minPayload: 1,
    maxPayload: 1,
    kind: "event",
  },
  "0xE0": {
    name: "ACK",
    desc: "Acuse de recibo. Payload: [acked_cmd, status].",
    fields: [],
    minPayload: 2,
    maxPayload: 2,
    kind: "ack",
  },
  "0xE1": {
    name: "NACK",
    desc: "Rechazo. Payload: [cmd, reason].",
    fields: [],
    minPayload: 2,
    maxPayload: 2,
    kind: "ack",
  },
};

export const PANEL_CLASS =
  "app-panel p-4";
export const INPUT_CLASS =
  "app-input w-full px-3 py-2 text-sm placeholder:text-slate-200";
export const SMALL_LABEL_CLASS =
  "mb-2 block text-xs font-medium uppercase tracking-[0.18em] text-slate-200";
export const NOTE_CLASS =
  "app-panel-strong border-l-2 border-cyan-400 p-3 text-sm text-slate-300";
export const BUTTON_CLASS =
  "app-button inline-flex items-center justify-center px-4 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/40";
export const GHOST_BUTTON_CLASS =
  "app-button--ghost inline-flex items-center justify-center px-4 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/40";

export const FRAME_SEGMENT_COLORS = [
  "bg-cyan-500/10 ring-cyan-400/45 text-cyan-100",
  "bg-emerald-500/10 ring-emerald-400/45 text-emerald-100",
  "bg-amber-500/10 ring-amber-400/45 text-amber-100",
  "bg-violet-500/10 ring-violet-400/45 text-violet-100",
  "bg-sky-500/10 ring-sky-400/45 text-sky-100",
  "bg-rose-500/10 ring-rose-400/45 text-rose-100",
  "bg-indigo-500/10 ring-indigo-400/45 text-indigo-100",
  "bg-lime-500/10 ring-lime-400/45 text-lime-100",
];
